# Generated by Django 3.2.4 on 2021-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vorname', models.CharField(max_length=50)),
                ('alter', models.IntegerField()),
                ('motif', models.TextField()),
                ('ladate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
