# Generated by Django 3.2.4 on 2021-06-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient00',
            name='alter',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient00',
            name='motif',
            field=models.TextField(blank=True),
        ),
    ]
