# Generated by Django 3.2.4 on 2021-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210626_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient00',
            name='alter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient00',
            name='motif',
            field=models.TextField(null=True),
        ),
    ]
